### Numpy 

In [1]:
import numpy as np


In [2]:
array = np.array([1,32,45,6])

In [3]:
print(array)

[ 1 32 45  6]


In [ ]:
## it do typecasting by itself like
array = np.array([1,32,45,6, "8"])
print(array)

['1' '32' '45' '6' '8']
<class 'numpy.ndarray'>


In [ ]:
### can make ND array make sure to be same element in each list inside array.. mean should be of same size
p_list = [[1],[2],[3]]
array = np.array(p_list)
print(array)

[[1]
 [2]
 [3]]


#### np array Attributes

In [8]:
array.shape

(3, 1)

In [ ]:
np.ones((2,3)) ## the inner value should be a tuple which is shape for nmpy array

array([[1., 1., 1.],
       [1., 1., 1.]])

In [15]:
zeros = np.zeros((3,4,5))
zeros.shape

(3, 4, 5)

In [ ]:
zeros = np.zeros([2,3,5])
zeros.shape

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [16]:
np.full((10,10), 5)

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5]])

In [17]:
np.eye(4,4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
np.arange(0,10,2)  ## this dirctly give me numpy list while python range function give me an iterator

array([0, 2, 4, 6, 8])

In [27]:
numbers = np.arange(0,11,2)

In [30]:
even_indexes = np.arange(0,10,2)
print(even_indexes)
numbers[even_indexes]

[0 2 4 6 8]


IndexError: index 6 is out of bounds for axis 0 with size 6

In [33]:
np.linspace(0,1,5)


array([0.  , 0.25, 0.5 , 0.75, 1.  ])

#### NUMPY BroadCasting

In [35]:
a = np.array([1,2,3,4,5])
b =5 
#b = np.array([6,7,8,9,10])
print(a+b)


[ 6  7  8  9 10]


In [48]:
a = np.random.randint(0,10, size = (5,5))
a


array([[9, 2, 2, 6, 2],
       [9, 6, 3, 8, 8],
       [7, 7, 5, 7, 3],
       [5, 9, 5, 4, 2],
       [8, 6, 4, 3, 4]], dtype=int32)

In [49]:
a[1:4, 1:4]


array([[6, 3, 8],
       [7, 5, 7],
       [9, 5, 4]], dtype=int32)

In [51]:
a = np.ones((6,6))
a

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [53]:
a.reshape(9,4)

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [55]:
a.reshape(3,12)

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

when we convert data into data into One-Hot. So we can back it take using "argmax()" function
so One-Hot and arg are opposite of each other

In [56]:
a.min()

np.float64(1.0)

In [ ]:
a.argmin() ### argmin gives the index of the minimum value

np.int64(0)

In [58]:
a.argmax()

np.int64(0)

np.squeez() and np. expand() are opposeite of each other